sudo: required
services:
 - docker

before_install:
 - docker build -t oluwashola/react-test -f ./client/Dockerfile.dev ./client

 
script:
 - docker run -e CI=true oluwashola/react-test npm test

after_success:
 - docker build -t oluwashola/multi-client ./client
 - docker build -t oluwashola/multi-nginx ./nginx   
 - docker build -t oluwashola/multi-server ./server   
 - docker build -t oluwashola/multi-worker ./worker

# Login to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
 - docker push oluwashola/multi-client
 - docker push oluwashola/multi-nginx
 - docker push oluwashola/multi-server
 - docker push oluwashola/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-934255252010'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY 